SELECT  T2.LABEL,T1.CREATE_Y,SUBSTR(T1.ERR_TYPE,0,LENGTH(T1.ERR_TYPE)-1) AS "ERR_TYPE",
SUBSTR(T1.ERR_INFO,0,LENGTH(T1.ERR_INFO)-1) AS "ERR_INFO"
FROM DCA_COMPANY_ERR_INFO_Y T1
INNER JOIN SYS_DICT T2
ON T1.COMPANY_ID= T2.VALUE AND T2.TYPE='company_name'