SELECT LABEL,CREATE_YM,ERR_TYPE,ERR_INFO
FROM(
SELECT  T2.LABEL,SUBSTR(T1.CREATE_YM,5) AS "CREATE_YM",SUBSTR(T1.ERR_TYPE,0,LENGTH(T1.ERR_TYPE)-1) AS "ERR_TYPE",
SUBSTR(T1.ERR_INFO,0,LENGTH(T1.ERR_INFO)-1) AS "ERR_INFO"
FROM DCA_COMPANY_ERR_INFO_M T1
INNER JOIN SYS_DICT T2
ON T1.COMPANY_ID= T2.VALUE AND T2.TYPE='company_name'
) 
WHERE CREATE_YM= :create_ym