SELECT T2.LABEL,TO_CHAR(T1.UPLOAD_TIME,'YY"年"MM"月"DD"日"') AS "DATE",TO_CHAR(T1.UPLOAD_TIME,'YY"年"MM"月"DD"日"') AS "DATE2"
FROM 
(SELECT  COMPANY_ID,UPLOAD_TIME
FROM DCA_COMPANY_ERR_INFO_M 
WHERE TO_CHAR(UPLOAD_TIME,'MM') = :uptime)T1
INNER JOIN SYS_DICT T2
ON T1.COMPANY_ID = T2.VALUE AND T2.TYPE ='company_name'