SELECT NVL(SUM(DATA_COUNT), 0) AS "c1"
FROM DCA_POWER_BIZ_DATA_COUNT
WHERE SUBSTR(POWER_ID,3,3) = :arr1
      AND TASK_NAME = :arr2
UNION ALL
SELECT COUNT(1)
FROM DCA_ALARM_DETAIL
WHERE SUBSTR(POWER_ID,3,3) = :arr1
      AND TASK_NAME = :arr2 AND ALARM_STATUS = '1'
UNION ALL
SELECT COUNT(1)
FROM DCA_RISK_MANAGE
WHERE SUBSTR(POWER_ID,3,3) = :arr1
      AND TASK_NAME = :arr2 AND (DEFINE_STATUS = '1' OR DEFINE_STATUS = '3')

