SELECT SUM(CNT) AS RISKCOUNT,TMP_NAME AS cname
FROM
(SELECT TEMP.CNT,CASE WHEN SUBSTR(TEMP.POWER_NAME,3,1)='A' THEN '投资运营'
WHEN SUBSTR(TEMP.POWER_NAME,3,1)='B' THEN '业绩考核'
WHEN SUBSTR(TEMP.POWER_NAME,3,1)='C' THEN '经营性资产监管'
WHEN SUBSTR(TEMP.POWER_NAME,3,1)='D' THEN '产权管理'
WHEN SUBSTR(TEMP.POWER_NAME,3,1)='E' THEN '财务监督'
WHEN SUBSTR(TEMP.POWER_NAME,3,1)='F' THEN '改革重组' END AS "TMP_NAME"
FROM (SELECT count(1) AS "CNT",T1.POWER_ID AS "POWER_NAME"
FROM  DCA_RISK_MANAGE T1
WHERE NVL(T1.POWER_ID,0)<> '0' AND (DEFINE_STATUS = '1' OR DEFINE_STATUS = '3')
GROUP BY T1.POWER_ID
ORDER BY T1.POWER_ID) TEMP)TMP
GROUP BY TMP_NAME
ORDER BY "LENGTH"(TMP_NAME)