select * from (SELECT T11.MON,T11.KEY, NVL((T11.CNT + T22.CNT),'0') AS "DATA_CNT"
FROM (
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-11),'MM') AS "MON",T1.VALUE AS "KEY",0 AS "CNT"
FROM SYS_DICT T1
WHERE T1.TYPE = 'define_status'
) T11
LEFT JOIN
(
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-11),'MM') AS "MON",T2.DEFINE_STATUS AS "KEY", COUNT(1) AS "CNT"
FROM DCA_CO_RISK_MANAGE T2
WHERE T2.CO_ID = :coid AND TO_CHAR(T2.CREATE_DATE,'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-11),'YYYYMM')
GROUP BY ROLLUP(T2.DEFINE_STATUS)
) T22
ON T11.KEY = T22.KEY
ORDER BY T11.KEY)
UNION ALL
select * from (SELECT T11.MON,T11.KEY, NVL((T11.CNT + T22.CNT),'0') AS "DATA_CNT"
FROM (
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-10),'MM') AS "MON",T1.VALUE AS "KEY",0 AS "CNT"
FROM SYS_DICT T1
WHERE T1.TYPE = 'define_status'
) T11
LEFT JOIN
(
SELECT  TO_CHAR(ADD_MONTHS(SYSDATE,-10),'MM') AS "MON",T2.DEFINE_STATUS AS "KEY", COUNT(1) AS "CNT"
FROM DCA_CO_RISK_MANAGE T2
WHERE T2.CO_ID = :coid AND TO_CHAR(T2.CREATE_DATE,'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-10),'YYYYMM')
GROUP BY ROLLUP(T2.DEFINE_STATUS)
) T22
ON T11.KEY = T22.KEY
ORDER BY T11.KEY)
UNION ALL
select * from (SELECT T11.MON,T11.KEY, NVL((T11.CNT + T22.CNT),'0') AS "DATA_CNT"
FROM (
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-9),'MM') AS "MON",T1.VALUE AS "KEY",0 AS "CNT"
FROM SYS_DICT T1
WHERE T1.TYPE = 'define_status'
) T11
LEFT JOIN
(
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-9),'MM') AS "MON",T2.DEFINE_STATUS AS "KEY", COUNT(1) AS "CNT"
FROM DCA_CO_RISK_MANAGE T2
WHERE T2.CO_ID = :coid AND TO_CHAR(T2.CREATE_DATE,'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-9),'YYYYMM')
GROUP BY ROLLUP(T2.DEFINE_STATUS)
) T22
ON T11.KEY = T22.KEY
ORDER BY T11.KEY)
UNION ALL
select * from (SELECT T11.MON,T11.KEY, NVL((T11.CNT + T22.CNT),'0') AS "DATA_CNT"
FROM (
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-8),'MM') AS "MON",T1.VALUE AS "KEY",0 AS "CNT"
FROM SYS_DICT T1
WHERE T1.TYPE = 'define_status'
) T11
LEFT JOIN
(
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-8),'MM') AS "MON",T2.DEFINE_STATUS AS "KEY", COUNT(1) AS "CNT"
FROM DCA_CO_RISK_MANAGE T2
WHERE T2.CO_ID = :coid AND TO_CHAR(T2.CREATE_DATE,'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-8),'YYYYMM')
GROUP BY ROLLUP(T2.DEFINE_STATUS)
) T22
ON T11.KEY = T22.KEY
ORDER BY T11.KEY)
UNION ALL
select * from (SELECT T11.MON,T11.KEY, NVL((T11.CNT + T22.CNT),'0') AS "DATA_CNT"
FROM (
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-7),'MM') AS "MON",T1.VALUE AS "KEY",0 AS "CNT"
FROM SYS_DICT T1
WHERE T1.TYPE = 'define_status'
) T11
LEFT JOIN
(
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-7),'MM') AS "MON",T2.DEFINE_STATUS AS "KEY", COUNT(1) AS "CNT"
FROM DCA_CO_RISK_MANAGE T2
WHERE T2.CO_ID = :coid AND TO_CHAR(T2.CREATE_DATE,'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-7),'YYYYMM')
GROUP BY ROLLUP(T2.DEFINE_STATUS)
) T22
ON T11.KEY = T22.KEY
ORDER BY T11.KEY)
UNION ALL
select * from (SELECT T11.MON,T11.KEY, NVL((T11.CNT + T22.CNT),'0') AS "DATA_CNT"
FROM (
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-6),'MM') AS "MON",T1.VALUE AS "KEY",0 AS "CNT"
FROM SYS_DICT T1
WHERE T1.TYPE = 'define_status'
) T11
LEFT JOIN
(
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-6),'MM') AS "MON",T2.DEFINE_STATUS AS "KEY", COUNT(1) AS "CNT"
FROM DCA_CO_RISK_MANAGE T2
WHERE T2.CO_ID = :coid AND TO_CHAR(T2.CREATE_DATE,'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-6),'YYYYMM')
GROUP BY ROLLUP(T2.DEFINE_STATUS)
) T22
ON T11.KEY = T22.KEY
ORDER BY T11.KEY)
UNION ALL
select * from (SELECT T11.MON,T11.KEY, NVL((T11.CNT + T22.CNT),'0') AS "DATA_CNT"
FROM (
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-5),'MM') AS "MON",T1.VALUE AS "KEY",0 AS "CNT"
FROM SYS_DICT T1
WHERE T1.TYPE = 'define_status'
) T11
LEFT JOIN
(
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-5),'MM') AS "MON",T2.DEFINE_STATUS AS "KEY", COUNT(1) AS "CNT"
FROM DCA_CO_RISK_MANAGE T2
WHERE T2.CO_ID = :coid AND TO_CHAR(T2.CREATE_DATE,'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-5),'YYYYMM')
GROUP BY ROLLUP(T2.DEFINE_STATUS)
) T22
ON T11.KEY = T22.KEY
ORDER BY T11.KEY)
UNION ALL
select * from (SELECT T11.MON,T11.KEY, NVL((T11.CNT + T22.CNT),'0') AS "DATA_CNT"
FROM (
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-4),'MM') AS "MON",T1.VALUE AS "KEY",0 AS "CNT"
FROM SYS_DICT T1
WHERE T1.TYPE = 'define_status'
) T11
LEFT JOIN
(
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-4),'MM') AS "MON",T2.DEFINE_STATUS AS "KEY", COUNT(1) AS "CNT"
FROM DCA_CO_RISK_MANAGE T2
WHERE T2.CO_ID = :coid AND TO_CHAR(T2.CREATE_DATE,'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-4),'YYYYMM')
GROUP BY ROLLUP(T2.DEFINE_STATUS)
) T22
ON T11.KEY = T22.KEY
ORDER BY T11.KEY)
UNION ALL
select * from (SELECT T11.MON,T11.KEY, NVL((T11.CNT + T22.CNT),'0') AS "DATA_CNT"
FROM (
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-3),'MM') AS "MON",T1.VALUE AS "KEY",0 AS "CNT"
FROM SYS_DICT T1
WHERE T1.TYPE = 'define_status'
) T11
LEFT JOIN
(
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-3),'MM') AS "MON",T2.DEFINE_STATUS AS "KEY", COUNT(1) AS "CNT"
FROM DCA_CO_RISK_MANAGE T2
WHERE T2.CO_ID = :coid AND TO_CHAR(T2.CREATE_DATE,'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-3),'YYYYMM')
GROUP BY ROLLUP(T2.DEFINE_STATUS)
) T22
ON T11.KEY = T22.KEY
ORDER BY T11.KEY)
UNION ALL
select * from (SELECT T11.MON,T11.KEY, NVL((T11.CNT + T22.CNT),'0') AS "DATA_CNT"
FROM (
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-2),'MM') AS "MON",T1.VALUE AS "KEY",0 AS "CNT"
FROM SYS_DICT T1
WHERE T1.TYPE = 'define_status'
) T11
LEFT JOIN
(
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-2),'MM') AS "MON",T2.DEFINE_STATUS AS "KEY", COUNT(1) AS "CNT"
FROM DCA_CO_RISK_MANAGE T2
WHERE T2.CO_ID = :coid AND TO_CHAR(T2.CREATE_DATE,'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-2),'YYYYMM')
GROUP BY ROLLUP(T2.DEFINE_STATUS)
) T22
ON T11.KEY = T22.KEY
ORDER BY T11.KEY)
UNION ALL
select * from (SELECT T11.MON,T11.KEY, NVL((T11.CNT + T22.CNT),'0') AS "DATA_CNT"
FROM (
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-1),'MM') AS "MON",T1.VALUE AS "KEY",0 AS "CNT"
FROM SYS_DICT T1
WHERE T1.TYPE = 'define_status'
) T11
LEFT JOIN
(
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-1),'MM') AS "MON",T2.DEFINE_STATUS AS "KEY", COUNT(1) AS "CNT"
FROM DCA_CO_RISK_MANAGE T2
WHERE T2.CO_ID = :coid AND TO_CHAR(T2.CREATE_DATE,'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-1),'YYYYMM')
GROUP BY ROLLUP(T2.DEFINE_STATUS)
) T22
ON T11.KEY = T22.KEY
ORDER BY T11.KEY)
UNION ALL
select * from (SELECT T11.MON,T11.KEY, NVL((T11.CNT + T22.CNT),'0') AS "DATA_CNT"
FROM (
SELECT TO_CHAR(SYSDATE,'MM') AS "MON",T1.VALUE AS "KEY",0 AS "CNT"
FROM SYS_DICT T1
WHERE T1.TYPE = 'define_status'
) T11
LEFT JOIN
(
SELECT TO_CHAR(SYSDATE,'MM') AS "MON",T2.DEFINE_STATUS AS "KEY", COUNT(1) AS "CNT"
FROM DCA_CO_RISK_MANAGE T2
WHERE T2.CO_ID = :coid AND TO_CHAR(T2.CREATE_DATE,'YYYYMM') = TO_CHAR(SYSDATE,'YYYYMM')
GROUP BY ROLLUP(T2.DEFINE_STATUS)
) T22
ON T11.KEY = T22.KEY
ORDER BY T11.KEY)