with "Tsub" as (SELECT T1."USER_ID",T1."USER_NAME",T1."COMMENT",T1."DATE",T1."EVENT",T1."No"
FROM 
(
SELECT  DISTINCT USER_ID,USER_NAME, '关于'||INSTANCE_INDEX_NAME || '事项' AS "COMMENT",
    TO_CHAR(START_TIME,'YYYY-MM-DD') AS "DATE",
    PATH_TITLE, 
   (CASE WHEN PATH_TITLE LIKE '%审批%' THEN '审核' ELSE '会议' END) AS "EVENT",
    DENSE_RANK() OVER(PARTITION BY USER_ID ORDER BY TO_CHAR(START_TIME,'YYYYMMDD') DESC) AS "No"
FROM DCA_PHY_HR_EFFORT
WHERE REMARK_STATE >= 0
) T1
WHERE T1."No" <= 3
ORDER BY USER_ID,T1."No"
)
SELECT "Tsub"."USER_ID","Tsub"."USER_NAME","Tsub"."DATE","Tsub"."EVENT",
 LISTAGG(to_char("Tsub"."COMMENT"), '||') WITHIN GROUP (ORDER BY "Tsub"."USER_ID","Tsub"."USER_NAME","Tsub"."DATE","Tsub"."EVENT") AS "COMMENT" 
FROM "Tsub"
GROUP BY "Tsub"."USER_ID","Tsub"."USER_NAME","Tsub"."DATE","Tsub"."EVENT"
ORDER BY "Tsub"."USER_ID","Tsub"."USER_NAME","Tsub"."DATE" DESC,"Tsub"."EVENT" ASC