SELECT CASE WHEN T11.KEY=10 THEN '高'
WHEN T11.KEY=20 THEN '中'
WHEN T11.KEY=30 THEN '低'  END AS KEY
,NVL(T22."CNT",0) AS "DATA_CNT"
FROM
(
SELECT T1.VALUE AS "KEY",0 AS "CNT"
FROM SYS_DICT T1
WHERE T1.TYPE = 'risk_level')T11
LEFT JOIN
(select T2.RISK_LEVEL, COUNT(1) AS  "CNT"
from DCA_CO_RISK_MANAGE T2
WHERE  T2.CO_ID = :cValue
GROUP BY T2.RISK_LEVEL)T22
ON T11.KEY=T22.RISK_LEVEL
ORDER BY T11.KEY
