WITH TOTAL(COL_NAME, CREATE_YYYY,CNT) AS (
SELECT :CNAME,TO_CHAR(ADD_MONTHS(SYSDATE,-12),'YY'),'' FROM DUAL
UNION
SELECT :CNAME,TO_CHAR(ADD_MONTHS(SYSDATE,-24),'YY'),'' FROM DUAL
UNION
SELECT :CNAME,TO_CHAR(ADD_MONTHS(SYSDATE,-36),'YY'),'' FROM DUAL
UNION
SELECT :CNAME,TO_CHAR(ADD_MONTHS(SYSDATE,-48),'YY'),'' FROM DUAL
UNION
SELECT :CNAME,TO_CHAR(ADD_MONTHS(SYSDATE,-60),'YY'),'' FROM DUAL
)
SELECT TOTAL.COL_NAME, TOTAL.CREATE_YYYY AS year, CASE WHEN TRIM(T1.ERR_INFO) IS NULL THEN N'0' ELSE TRIM(T1.ERR_INFO) END AS "ERRORS"
FROM TOTAL
LEFT JOIN
(
select T2.LABEL,T1.CREATE_Y,T1.ERR_INFO
from DCA_COMPANY_ERR_INFO_Y T1
INNER JOIN SYS_DICT T2
ON T1.COMPANY_ID =T2.VALUE AND T2.TYPE='company_name'
WHERE  LABEL =:CNAME
) T1
ON   SUBSTR(T1.CREATE_Y,3,2) = TOTAL.CREATE_YYYY
ORDER BY CREATE_YYYY
