SELECT CASE WHEN T11.KEY=1 THEN '风险'
WHEN T11.KEY=2 THEN '非风险'
 WHEN T11.KEY=3 THEN '未界定' END AS "KEY"
,NVL(T22."CNT",0) AS "DATA_CNT"
FROM
(
SELECT T1.VALUE AS "KEY",0 AS "CNT"
FROM SYS_DICT T1
WHERE T1.TYPE = 'define_status')T11
LEFT JOIN
(select T2.DEFINE_STATUS, COUNT(1) AS  "CNT"
from DCA_CO_RISK_MANAGE T2
WHERE  T2.CO_ID = :cValue
GROUP BY T2.DEFINE_STATUS)T22
ON T11.KEY=T22.DEFINE_STATUS
ORDER BY T11.KEY
