SELECT T11.KEY AS "RISK_NAME",NVL(T22.RISK_CNT+T11.CNT,'0') AS "RISK_CNT"
FROM
(SELECT T1.VALUE, T1.LABEL AS "KEY",0 AS "CNT"
FROM SYS_DICT T1
WHERE T1.TYPE = 'alarm_type'
ORDER BY T1.VALUE)T11
LEFT JOIN
(
SELECT T2.ALARM_TYPE AS "RISK_TYPE",COUNT(1) AS "RISK_CNT"
FROM DCA_RISK_MANAGE T2
WHERE SUBSTR(T2.POWER_ID,1,2) = :pop1
      AND T2.TASK_NAME = :pop2 AND T2.DEFINE_STATUS IN('1','3')
GROUP BY T2.ALARM_TYPE
) T22
ON T11.VALUE=T22.RISK_TYPE

