SELECT T11.ALARM_JIDU,NVL(T22.ALARM_CNT,0) AS alarmCount,T11.RISK_JIDU,NVL(T22.RISK_CNT,0) AS riskCount FROM 
(
SELECT '1' AS "ALARM_JIDU",0 AS "ALARM_CNT",'1' AS "RISK_JIDU",0 AS "RISK_CNT"
FROM DUAL
UNION
SELECT '2' AS "ALARM_JIDU",0 AS "ALARM_CNT",'2' AS "RISK_JIDU",0 AS "RISK_CNT"
FROM DUAL
UNION
SELECT '3' AS "ALARM_JIDU",0 AS "ALARM_CNT",'3' AS "RISK_JIDU",0 AS "RISK_CNT"
FROM DUAL
UNION
SELECT '4' AS "ALARM_JIDU",0 AS "ALARM_CNT",'4' AS "RISK_JIDU",0 AS "RISK_CNT"
FROM DUAL)T11
LEFT JOIN
(
SELECT T1.ALARM_JIDU,T1.ALARM_CNT,T2.RISK_JIDU,T2.RISK_CNT
FROM
(
SELECT COUNT(1) AS "ALARM_CNT",TO_CHAR(CREATE_DATE,'q') AS "ALARM_JIDU"
FROM DCA_ALARM_DETAIL TT1 WHERE TO_CHAR(CREATE_DATE,'YYYY')=TO_CHAR(SYSDATE,'YYYY')   GROUP BY TO_CHAR(CREATE_DATE,'q')
) T1
FULL JOIN
 (SELECT COUNT(1) AS "RISK_CNT",TO_CHAR(CREATE_DATE,'q') AS "RISK_JIDU"
FROM DCA_RISK_MANAGE T2 WHERE TO_CHAR(CREATE_DATE,'YYYY')=TO_CHAR(SYSDATE,'YYYY')  GROUP BY TO_CHAR(CREATE_DATE,'q')
) T2
ON T1.ALARM_JIDU = T2.RISK_JIDU
ORDER BY T1.ALARM_JIDU
)T22
ON T11.ALARM_JIDU =T22.ALARM_JIDU
ORDER BY T11.ALARM_JIDU