WITH "TOTAL_RISK" AS (
SELECT TO_CHAR("TT1"."LABEL")  AS "NAME" ,NVL("TT2"."RISK_PERCENT",0) AS "RISK_PERCENT"
FROM
(SELECT  "T1"."VALUE", "T1"."LABEL" AS "LABEL", '0' AS "RISK_PERCENT"
FROM "SYS_DICT" "T1"
WHERE "T1"."TYPE" ='risk_type_detail'  AND  "T1"."VALUE" != '06' AND  "T1"."VALUE" != '07') "TT1"
LEFT JOIN
(SELECT "TOTAL"."LABEL" AS "RISK_NAME",
 CASE WHEN "TOTAL"."RISK_TOTAL" = 0 THEN 0 ELSE ROUND("RESULT"."RISK_CNT"/"TOTAL"."RISK_TOTAL",2) END AS "RISK_PERCENT"
FROM 
(
SELECT "T4"."VALUE","T4"."LABEL",COUNT(1) AS "RISK_TOTAL"
FROM "DCA_WORKFLOW_TASK_CONTENT" "T1"
INNER JOIN "DCA_POWER_BIZ_DATA_COUNT" "T2"
ON "T1"."TASK_ID" = "T2"."TASK_ID" AND "T1"."ALARM_TYPE" != '1'
INNER JOIN "DCA_ALARM_RISK_LIST" "T3"
ON "T1"."RISK_ID" = "T3"."RISK_ID"
INNER JOIN "SYS_DICT" "T4"
ON  "T3"."RISK_TYPE" = "T4"."VALUE" AND "T4"."TYPE" = 'risk_type_detail'
     AND  "T4"."VALUE" != '06' AND  "T4"."VALUE" != '07'
GROUP BY "T4"."VALUE","T4"."LABEL"
order by "T4"."VALUE","T4"."LABEL"
) "TOTAL"
INNER JOIN
(
SELECT "T3"."VALUE","T3"."LABEL",COUNT(1) AS "RISK_CNT"
FROM "DCA_ALARM_RISK_LIST" "T1"
INNER JOIN "DCA_RISK_MANAGE" "T2"
ON "T1"."RISK_ID" = "T2"."RISK_ID" AND "T2"."ALARM_TYPE" != '1'
INNER JOIN "SYS_DICT" "T3"
ON  "T1"."RISK_TYPE" = "T3"."VALUE" AND "T3"."TYPE" = 'risk_type_detail' AND  "T3"."VALUE" != '06' AND  "T3"."VALUE" != '07'
GROUP BY "T3"."VALUE","T3"."LABEL"
order by "T3"."VALUE","T3"."LABEL"
)  "RESULT"
ON "TOTAL"."VALUE" = "RESULT"."VALUE") "TT2"
ON "TT1"."LABEL" = "TT2"."RISK_NAME"
),
"TIME" AS 
(
SELECT TO_CHAR("TT1"."LABEL") AS "NAME" ,NVL("TIME_RISK"."RISK_PERCENT",0) AS "RISK_PERCENT"
FROM
(SELECT  "T1"."VALUE", "T1"."LABEL" AS "LABEL", '0' AS "RISK_PERCENT"
FROM "SYS_DICT" "T1"
WHERE "T1"."TYPE" ='risk_type_detail'  AND  "T1"."VALUE" = '06') "TT1"
LEFT JOIN
(
SELECT "TIME_T"."VALUE" AS "RISK_VALUE",
 CASE WHEN "TIME_T"."RISK_TIME_T" = 0 THEN 0 ELSE ROUND("TIME_R"."RISK_CNT"/"TIME_T"."RISK_TIME_T",2) END AS "RISK_PERCENT"
FROM 
(
SELECT TO_CHAR('06') AS "VALUE" , COUNT(1) AS "RISK_TIME_T"
FROM "DCA_POWER_BIZ_DATA_COUNT" "T1"
INNER JOIN "DCA_WORKFLOW_TASK_CONTENT" "T2"
ON "T1"."TASK_ID" = "T2"."TASK_ID" AND "T2"."ALARM_TYPE" = '1'
INNER JOIN "DCA_ALARM_RISK_LIST" "T3"
ON "T2"."RISK_ID" = "T3"."RISK_ID"
) "TIME_T"
INNER JOIN
(
SELECT TO_CHAR('06') AS "VALUE" ,COUNT(1) AS "RISK_CNT"
FROM "DCA_ALARM_RISK_LIST" "T1"
INNER JOIN "DCA_RISK_MANAGE" "T2"
ON "T1"."RISK_ID" = "T2"."RISK_ID" AND "T2"."ALARM_TYPE" = '1'
)  "TIME_R"
ON "TIME_T"."VALUE" = "TIME_R"."VALUE"
) "TIME_RISK"
ON "TT1"."VALUE" = "TIME_RISK"."RISK_VALUE"
)
SELECT "TOTAL_RISK"."NAME", "TOTAL_RISK"."RISK_PERCENT" FROM "TOTAL_RISK"
UNION ALL
SELECT "TIME"."NAME", "TIME"."RISK_PERCENT" FROM "TIME"
UNION ALL
SELECT "TEMP"."LABEL" AS "NAME", 0 AS "RISK_PERCENT"
FROM "SYS_DICT" "TEMP" WHERE "TEMP"."TYPE" = 'risk_type_detail' AND "TEMP"."VALUE" = '07'

