SELECT TEMP."TYPE", TEMP."COMMENT"
FROM (
SELECT TO_CHAR(T1.UPDATE_DATE,'YYYY-MM-DD HH24:MI:SS') AS "TIME", '风险：' AS "TYPE", T2.NAME || '  于 ' || TO_CHAR(T1.UPDATE_DATE,'YYYY-MM-DD HH24:MI:SS') || '  出现风险' AS "COMMENT"
FROM DCA_RISK_MANAGE T1
INNER JOIN SYS_USER T2
ON T1.BIZ_OPER_PERSON_ID = T2.ID
WHERE SUBSTR(T1.POWER_ID,3,3) = :arr
      AND TASK_NAME IN ('拟办人意见','拟办负责人审批','专委会审批意见核准','专委会成员签名','专委会领导审批','分管领导审批','主要领导审批')
      AND (T1.DEFINE_STATUS = '1' OR T1.DEFINE_STATUS = '3')
UNION ALL
SELECT TO_CHAR(T1.UPDATE_DATE,'YYYY-MM-DD HH24:MI:SS') AS "TIME", '告警：' AS "TYPE", T2.NAME ||  '  于 ' || TO_CHAR(T1.UPDATE_DATE,'YYYY-MM-DD HH24:MI:SS') || '  出现告警' AS "COMMENT"
FROM DCA_ALARM_DETAIL T1
INNER JOIN SYS_USER T2
ON T1.BIZ_OPER_PERSON_ID = T2.ID
WHERE SUBSTR(POWER_ID,3,3) = :arr
      AND TASK_NAME IN ('拟办人意见','拟办负责人审批','专委会审批意见核准','专委会成员签名','专委会领导审批','分管领导审批','主要领导审批')
      AND ALARM_STATUS = '1'
) TEMP
ORDER BY TEMP.TIME DESC