SELECT CASE WHEN T11.KEY=2 THEN '黄色'
 WHEN T11.KEY=3 THEN '橙色'
 WHEN T11.KEY=4 THEN '红色' END  AS "KEY"
,NVL(T22."CNT",0) AS "DATA_CNT"
FROM
(
SELECT T1.VALUE AS "KEY",0 AS "CNT"
FROM SYS_DICT T1
WHERE T1.TYPE = 'alarm_level'
AND T1.VALUE IN ('2','3','4'))T11
LEFT JOIN
(select T2.ALARM_LEVEL, COUNT(1) AS  "CNT" 
from DCA_CO_ALARM_DETAIL T2     
WHERE  T2.CO_ID = :cValue
GROUP BY T2.ALARM_LEVEL)T22
ON T11.KEY=T22.ALARM_LEVEL
ORDER BY T11.KEY DESC