select 
(SELECT COUNT(1)
FROM DCA_RISK_MANAGE T1
WHERE T1.ALARM_LEVEL='4') as "redRisk",
(SELECT COUNT(1)
FROM DCA_RISK_MANAGE T1
WHERE  T1.ALARM_LEVEL='4' and (T1.DEFINE_STATUS='1' or T1.DEFINE_STATUS='2' )) as "redRiskDone",
(SELECT COUNT(1)
FROM DCA_RISK_MANAGE T1
WHERE T1.ALARM_LEVEL='3') as "orangeRisk",
(SELECT COUNT(1)
FROM DCA_RISK_MANAGE T1
WHERE  T1.ALARM_LEVEL='3' and (T1.DEFINE_STATUS='1' or T1.DEFINE_STATUS='2' )) as "orangeRiskDone",
(SELECT COUNT(1)
FROM DCA_RISK_MANAGE T1
WHERE T1.ALARM_LEVEL='2') as "yellowRisk",
(SELECT COUNT(1)
FROM DCA_RISK_MANAGE T1
WHERE  T1.ALARM_LEVEL='2' and (T1.DEFINE_STATUS='1' or T1.DEFINE_STATUS='2' )) as "yellowRiskDone"
from dual
union all
select 
(SELECT COUNT(1)
FROM DCA_ALARM_DETAIL T2
WHERE T2.ALARM_LEVEL='4') as "redAlarm",
(SELECT COUNT(1)
FROM DCA_ALARM_DETAIL T2
WHERE  T2.ALARM_LEVEL='4' and T2.ALARM_STATUS='1' ) as "redAlarmDone",
(SELECT COUNT(1)
FROM DCA_ALARM_DETAIL T2
WHERE T2.ALARM_LEVEL='3') as "orangeAlarm",
(SELECT COUNT(1)
FROM DCA_ALARM_DETAIL T2
WHERE  T2.ALARM_LEVEL='3' and T2.ALARM_STATUS='1' ) as "orangeAlarmDone",
(SELECT COUNT(1)
FROM DCA_ALARM_DETAIL T2
WHERE T2.ALARM_LEVEL='2') as "yellowAlarm",
(SELECT COUNT(1)
FROM DCA_ALARM_DETAIL T2
WHERE  T2.ALARM_LEVEL='2' and T2.ALARM_STATUS='1' ) as "yellowAlarmDone"
from dual
