SELECT T11.CREATE_YM,T22.LABEL,T22.DD
FROM 
(
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-11),'YYYYMM') AS "CREATE_YM",null  AS "LABEL",NULL AS "DD"
FROM DUAL
UNION 
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-10),'YYYYMM') AS "CREATE_YM",null  AS "LABEL",NULL AS "DD"
FROM DUAL
UNION 
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-9),'YYYYMM') AS "CREATE_YM",null  AS "LABEL",NULL AS "DD"
FROM DUAL
UNION 
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-8),'YYYYMM') AS "CREATE_YM",null  AS "LABEL",NULL AS "DD"
FROM DUAL
UNION 
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-7),'YYYYMM') AS "CREATE_YM",null  AS "LABEL",NULL AS "DD"
FROM DUAL
UNION 
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-6),'YYYYMM') AS "CREATE_YM",null  AS "LABEL",NULL AS "DD"
FROM DUAL
UNION 
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-5),'YYYYMM') AS "CREATE_YM",null  AS "LABEL",NULL AS "DD"
FROM DUAL
UNION 
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-4),'YYYYMM') AS "CREATE_YM",null  AS "LABEL",NULL AS "DD"
FROM DUAL
UNION 
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-3),'YYYYMM') AS "CREATE_YM", null AS "LABEL",NULL AS "DD"
FROM DUAL
UNION 
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-2),'YYYYMM') AS "CREATE_YM",null AS "LABEL",NULL AS "DD"
FROM DUAL
UNION 
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-1),'YYYYMM') AS "CREATE_YM",null AS "LABEL",NULL AS "DD"
FROM DUAL
UNION
SELECT TO_CHAR(SYSDATE,'YYYYMM') AS "CREATE_YM",null AS "LABEL",NULL AS "DD"
FROM DUAL
)T11
LEFT JOIN 
(
SELECT TO_CHAR(CREATE_YM)AS  "CREATE_YM" ,LABEL,DD
FROM
(SELECT  T2.LABEL，T1.CREATE_YM,TO_CHAR(UPLOAD_TIME,'DD') AS "DD"
FROM DCA_COMPANY_ERR_INFO_M T1
INNER JOIN SYS_DICT T2
ON T1.COMPANY_ID= T2.VALUE AND T2.TYPE='company_name')
WHERE LABEL= :co_name
)T22
ON T11.CREATE_YM=T22.CREATE_YM
ORDER BY T11.CREATE_YM
