SELECT TO_CHAR(A1) AS "dataCount",CASE WHEN A1=0 THEN TO_CHAR(0) ELSE TO_CHAR(ROUND((A1-A2-A3)/A1,2)*100) END AS "effectNum"
FROM (SELECT (select SUM(DATA_COUNT) from DCA_POWER_BIZ_DATA_COUNT ) AS A1,
(select count(1) from DCA_ALARM_DETAIL
WHERE DEL_FLAG ='0' ) AS A2,
(select count(1) from DCA_RISK_MANAGE
WHERE DEL_FLAG ='0'  ) AS A3
FROM DUAL)