SELECT POWER_NAME,ONE||','||TWO||','||THREE||','||FOUR||','||FIVE||','||SIX||','||SEVEN||','||EIGHT||','||NINE||','||TEN||','||ELEVEN||','||TWELVE AS "DATA_CNT" 
FROM (SELECT POWER_NAME,
 SUM(CASE WHEN TO_CHAR(CREATE_DATE, 'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE, -11), 'YYYYMM')THEN 1 ELSE 0 END) AS "ONE",
 SUM(CASE WHEN TO_CHAR(CREATE_DATE, 'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE, -10), 'YYYYMM')THEN 1 ELSE 0 END) AS "TWO",
 SUM(CASE WHEN TO_CHAR(CREATE_DATE, 'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE, -9), 'YYYYMM')THEN 1 ELSE 0 END) AS "THREE",
 SUM(CASE WHEN TO_CHAR(CREATE_DATE, 'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE, -8), 'YYYYMM')THEN 1 ELSE 0 END) AS "FOUR",
 SUM(CASE WHEN TO_CHAR(CREATE_DATE, 'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE, -7), 'YYYYMM')THEN 1 ELSE 0 END) AS "FIVE",
 SUM(CASE WHEN TO_CHAR(CREATE_DATE, 'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE, -6), 'YYYYMM')THEN 1 ELSE 0 END) AS "SIX",
 SUM(CASE WHEN TO_CHAR(CREATE_DATE, 'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE, -5), 'YYYYMM')THEN 1 ELSE 0 END) AS "SEVEN",
 SUM(CASE WHEN TO_CHAR(CREATE_DATE, 'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE, -4), 'YYYYMM')THEN 1 ELSE 0 END) AS "EIGHT",
 SUM(CASE WHEN TO_CHAR(CREATE_DATE, 'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE, -3), 'YYYYMM')THEN 1 ELSE 0 END) AS "NINE",
 SUM(CASE WHEN TO_CHAR(CREATE_DATE, 'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE, -2), 'YYYYMM')THEN 1 ELSE 0 END) AS "TEN",
 SUM(CASE WHEN TO_CHAR(CREATE_DATE, 'YYYYMM') = TO_CHAR(ADD_MONTHS(SYSDATE, -1), 'YYYYMM')THEN 1 ELSE 0 END) AS "ELEVEN",
 SUM(CASE WHEN TO_CHAR(CREATE_DATE, 'YYYYMM') = TO_CHAR(SYSDATE, 'YYYYMM')THEN 1 ELSE 0 END) AS "TWELVE"
 FROM DCA_CO_RISK_MANAGE
 WHERE CO_ID = :coid
 GROUP BY POWER_NAME)
