SELECT TO_CHAR(SYSDATE,'YYYY')||'01' AS "MON", COUNT(1) AS "DATA_COUNT"
FROM DCA_RISK_MANAGE
WHERE SUBSTR(POWER_ID,1,2) = :arr1
        AND SUBSTR(POWER_ID,3,1)= :arr2
        AND (DEFINE_STATUS = '1' OR DEFINE_STATUS = '3')
        AND TO_CHAR(CREATE_DATE,'YYYYMM')=TO_CHAR(SYSDATE,'YYYY')||'01' 
UNION
SELECT TO_CHAR(SYSDATE,'YYYY')||'02' AS "MON", COUNT(1) AS "DATA_COUNT"
FROM DCA_RISK_MANAGE
WHERE SUBSTR(POWER_ID,1,2) = :arr1
        AND SUBSTR(POWER_ID,3,1)=:arr2
        AND (DEFINE_STATUS = '1' OR DEFINE_STATUS = '3')
        AND TO_CHAR(CREATE_DATE,'YYYYMM')=TO_CHAR(SYSDATE,'YYYY')||'02'
UNION
SELECT TO_CHAR(SYSDATE,'YYYY')||'03' AS "MON", COUNT(1) AS "DATA_COUNT"
FROM DCA_RISK_MANAGE
WHERE SUBSTR(POWER_ID,1,2) = :arr1
        AND SUBSTR(POWER_ID,3,1)=:arr2
        AND (DEFINE_STATUS = '1' OR DEFINE_STATUS = '3')
        AND TO_CHAR(CREATE_DATE,'YYYYMM')=TO_CHAR(SYSDATE,'YYYY')||'03'
UNION
SELECT TO_CHAR(SYSDATE,'YYYY')||'04' AS "MON", COUNT(1) AS "DATA_COUNT"
FROM DCA_RISK_MANAGE
WHERE SUBSTR(POWER_ID,1,2) = :arr1
        AND SUBSTR(POWER_ID,3,1)=:arr2
        AND (DEFINE_STATUS = '1' OR DEFINE_STATUS = '3')
        AND TO_CHAR(CREATE_DATE,'YYYYMM')=TO_CHAR(SYSDATE,'YYYY')||'04'
UNION
SELECT TO_CHAR(SYSDATE,'YYYY')||'05' AS "MON", COUNT(1) AS "DATA_COUNT"
FROM DCA_RISK_MANAGE
WHERE SUBSTR(POWER_ID,1,2) = :arr1
        AND SUBSTR(POWER_ID,3,1)= :arr2
        AND (DEFINE_STATUS = '1' OR DEFINE_STATUS = '3')
        AND TO_CHAR(CREATE_DATE,'YYYYMM')=TO_CHAR(SYSDATE,'YYYY')||'05'
UNION
SELECT TO_CHAR(SYSDATE,'YYYY')||'06' AS "MON", COUNT(1) AS "DATA_COUNT"
FROM DCA_RISK_MANAGE
WHERE SUBSTR(POWER_ID,1,2) = :arr1
        AND SUBSTR(POWER_ID,3,1)=:arr2
        AND (DEFINE_STATUS = '1' OR DEFINE_STATUS = '3')
        AND TO_CHAR(CREATE_DATE,'YYYYMM')=TO_CHAR(SYSDATE,'YYYY')||'06'
UNION
SELECT TO_CHAR(SYSDATE,'YYYY')||'07' AS "MON", COUNT(1) AS "DATA_COUNT"
FROM DCA_RISK_MANAGE
WHERE SUBSTR(POWER_ID,1,2) = :arr1
        AND SUBSTR(POWER_ID,3,1)=:arr2
        AND (DEFINE_STATUS = '1' OR DEFINE_STATUS = '3')
        AND TO_CHAR(CREATE_DATE,'YYYYMM')=TO_CHAR(SYSDATE,'YYYY')||'07'
UNION
SELECT TO_CHAR(SYSDATE,'YYYY')||'08' AS "MON", COUNT(1) AS "DATA_COUNT"
FROM DCA_RISK_MANAGE
WHERE SUBSTR(POWER_ID,1,2) = :arr1
        AND SUBSTR(POWER_ID,3,1)=:arr2
        AND (DEFINE_STATUS = '1' OR DEFINE_STATUS = '3')
        AND TO_CHAR(CREATE_DATE,'YYYYMM')=TO_CHAR(SYSDATE,'YYYY')||'08'
UNION
SELECT TO_CHAR(SYSDATE,'YYYY')||'09' AS "MON", COUNT(1) AS "DATA_COUNT"
FROM DCA_RISK_MANAGE
WHERE SUBSTR(POWER_ID,1,2) = :arr1
        AND SUBSTR(POWER_ID,3,1)= :arr2
        AND (DEFINE_STATUS = '1' OR DEFINE_STATUS = '3')
        AND TO_CHAR(CREATE_DATE,'YYYYMM')=TO_CHAR(SYSDATE,'YYYY')||'09'
UNION
SELECT TO_CHAR(SYSDATE,'YYYY')||'10' AS "MON", COUNT(1) AS "DATA_COUNT"
FROM DCA_RISK_MANAGE
WHERE SUBSTR(POWER_ID,1,2) = :arr1
        AND SUBSTR(POWER_ID,3,1)= :arr2
        AND (DEFINE_STATUS = '1' OR DEFINE_STATUS = '3')
        AND TO_CHAR(CREATE_DATE,'YYYYMM')=TO_CHAR(SYSDATE,'YYYY')||'10'
UNION
SELECT TO_CHAR(SYSDATE,'YYYY')||'11' AS "MON", COUNT(1) AS "DATA_COUNT"
FROM DCA_RISK_MANAGE
WHERE SUBSTR(POWER_ID,1,2) = :arr1
        AND SUBSTR(POWER_ID,3,1)=:arr2
        AND (DEFINE_STATUS = '1' OR DEFINE_STATUS = '3')
        AND TO_CHAR(CREATE_DATE,'YYYYMM')=TO_CHAR(SYSDATE,'YYYY')||'11'
UNION
SELECT TO_CHAR(SYSDATE,'YYYY')||'12' AS "MON", COUNT(1) AS "DATA_COUNT"
FROM DCA_RISK_MANAGE
WHERE SUBSTR(POWER_ID,1,2) = :arr1
        AND SUBSTR(POWER_ID,3,1)= :arr2
        AND (DEFINE_STATUS = '1' OR DEFINE_STATUS = '3')
        AND TO_CHAR(CREATE_DATE,'YYYYMM')=TO_CHAR(SYSDATE,'YYYY')||'12'