package com.dpn.dpows.standard.model;import java.util.Date;

/*** WorkDeclareDtoDto.*
* @author zhaoqian@dpn.com.cn
* @since 1.0.0 zhaoqian@dpn.com.cn
* @version 1.0.0 zhaoqian@dpn.com.cn
* Created by ZhaoQian on 2017-9-6 14:27:26
**/
public class WorkDeclareFeedbackDto {
						// 字段              字段名         字段类型         是否可为空
	private String declare_goods_id;    // 申报货物ID  VARCHAR2(32)   N	private String declare_id;			//申报ID VARCHAR2(32) N	private String imdg_no;			//国际危规编号	private String imdg_name;		//国际危货名称	private Double declare_num;	//申报量	private Double work_num;		//作业量	private Date real_time_start;  //作业实际开始时间	private Date real_time_end;  //作业实际结束时间	private String feedback_user_id;  //反馈人员用户ID	private Integer feedback_status; //反馈状态	
	public String getDeclare_goods_id() {		return declare_goods_id;	}	public void setDeclare_goods_id(String declare_goods_id) {		this.declare_goods_id = declare_goods_id;	}	public String getDeclare_id() {		return declare_id;	}	public void setDeclare_id(String declare_id) {		this.declare_id = declare_id;	}	public String getImdg_no() {		return imdg_no;	}	public void setImdg_no(String imdg_no) {		this.imdg_no = imdg_no;	}	public String getImdg_name() {		return imdg_name;	}	public void setImdg_name(String imdg_name) {		this.imdg_name = imdg_name;	}	public Double getDeclare_num() {		return declare_num;	}	public void setDeclare_num(Double declare_num) {		this.declare_num = declare_num;	}	public Double getWork_num() {		return work_num;	}	public void setWork_num(Double work_num) {		this.work_num = work_num;	}	public Date getReal_time_start() {		return real_time_start;	}	public void setReal_time_start(Date real_time_start) {		this.real_time_start = real_time_start;	}	public Date getReal_time_end() {		return real_time_end;	}	public void setReal_time_end(Date real_time_end) {		this.real_time_end = real_time_end;	}	public String getFeedback_user_id() {		return feedback_user_id;	}	public void setFeedback_user_id(String feedback_user_id) {		this.feedback_user_id = feedback_user_id;	}	public Integer getFeedback_status() {		return feedback_status;	}	public void setFeedback_status(Integer feedback_status) {		this.feedback_status = feedback_status;	}	public String getFeedback_not_text() {		return feedback_not_text;	}	public void setFeedback_not_text(String feedback_not_text) {		this.feedback_not_text = feedback_not_text;	}	public Date getGmt_created() {		return gmt_created;	}	public void setGmt_created(Date gmt_created) {		this.gmt_created = gmt_created;	}	public String getId() {		return id;	}	public void setId(String id) {		this.id = id;	}	private String feedback_not_text;  //不反馈原因	private Date gmt_created;  // 创建时间	private String  id; // id
}
