/** 工作流状态字典数据 **/
/** START **/

INSERT INTO "SYS_DICT" VALUES ('180', '-999999999', '纪检监察室', 'discipline_depart', '纪检监察室', 10, '0', '1', TO_TIMESTAMP(' 2016-11-29 00:00:00:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', TO_TIMESTAMP(' 2016-11-29 00:00:00:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'), NULL, '0');
INSERT INTO "SYS_DICT" VALUES ('181', '-888888888', '纪检监察室领导', 'discipline_depart_leader', '纪检监察室领导', 20, '0', '1', TO_TIMESTAMP(' 2016-11-29 00:00:00:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', TO_TIMESTAMP(' 2016-11-29 00:00:00:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'), NULL, '0');

/** END **/