package com.dhc.authorization.delegate.domain;

import com.dhc.organization.common.data.BaseVO;

public class WF_ORG_DELEITEM extends BaseVO {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_DELEITEM.DELE_ID
	 */
	private String deleId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_DELEITEM.DI_PRIV_ID
	 */
	private String diPrivId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_DELEITEM.DI_PRIV_TYPE
	 */
	private String diPrivType;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_DELEITEM.DI_PRIV_NAME
	 */
	private String diPrivName;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_DELEITEM.DELE_ID
	 *
	 * @return the value of WF_ORG_DELEITEM.DELE_ID
	 */
	public String getDeleId() {
		return deleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_DELEITEM.DELE_ID
	 *
	 * @param deleId
	 *            the value for WF_ORG_DELEITEM.DELE_ID
	 */
	public void setDeleId(String deleId) {
		this.deleId = deleId == null ? null : deleId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_DELEITEM.DI_PRIV_ID
	 *
	 * @return the value of WF_ORG_DELEITEM.DI_PRIV_ID
	 */
	public String getDiPrivId() {
		return diPrivId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_DELEITEM.DI_PRIV_ID
	 *
	 * @param diPrivId
	 *            the value for WF_ORG_DELEITEM.DI_PRIV_ID
	 */
	public void setDiPrivId(String diPrivId) {
		this.diPrivId = diPrivId == null ? null : diPrivId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_DELEITEM.DI_PRIV_TYPE
	 *
	 * @return the value of WF_ORG_DELEITEM.DI_PRIV_TYPE
	 */
	public String getDiPrivType() {
		return diPrivType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_DELEITEM.DI_PRIV_TYPE
	 *
	 * @param diPrivType
	 *            the value for WF_ORG_DELEITEM.DI_PRIV_TYPE
	 */
	public void setDiPrivType(String diPrivType) {
		this.diPrivType = diPrivType == null ? null : diPrivType.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_DELEITEM.DI_PRIV_NAME
	 *
	 * @return the value of WF_ORG_DELEITEM.DI_PRIV_NAME
	 */
	public String getDiPrivName() {
		return diPrivName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_DELEITEM.DI_PRIV_NAME
	 *
	 * @param diPrivName
	 *            the value for WF_ORG_DELEITEM.DI_PRIV_NAME
	 */
	public void setDiPrivName(String diPrivName) {
		this.diPrivName = diPrivName == null ? null : diPrivName.trim();
	}
}