package cn.rkylin.oms.system.menu.domain;

import java.util.List;

import cn.rkylin.oms.common.base.BaseEntity;

/**
 *<p>
 * 描述: 菜单访问对象
 * </p>
 *
 */
public class WF_ORG_MENU extends BaseEntity {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_MENU.MENU_CODE
	 */
	private String menuCode;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_MENU.PARENT_MENU_CODE
	 */
	private String parentMenuCode;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_MENU.MENU_NAME
	 */
	private String menuName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_MENU.MENU_AREA
	 */
	private String menuArea;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_MENU.MENU_LOCATION
	 */
	private String menuLocation;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_MENU.MENU_IMG_LOCATION
	 */
	private String menuImgLocation;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_MENU.MENU_DESC
	 */
	private String menuDesc;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_MENU.MENU_ORDER
	 */
	private int menuOrder;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_MENU.MENU_ELEMENT_ID
	 */
	private String menuElementId;

	private String menuElementType;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_MENU.MENU_TYPE
	 */
	private String menuType;

	private String menuIsDefault;

	private int menuLevel;

	private int maxValue;

	private List<String> userIdTemp;

	/**
	 * 用于查询菜单时，指定可使用，还是可分配
	 */
	private String authorityType;

	/**
	 * 用于查询菜单项的时候，把userID作为参数
	 */
	private String userID;

	/**
	 * 来自系统环境变量中的“菜单分类标识”，例如：将子系统名作为菜单分类标识， 可以实现例如不同的子系统看到的菜单不一样
	 */
	private String menuCategory;

	/**
	 * 用于指定角色类型作为查询条件
	 */
	private String roleType;

	public String getMenuCategory() {
		return menuCategory;
	}

	public void setMenuCategory(String menuCategory) {
		this.menuCategory = menuCategory;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_MENU.MENU_CODE
	 *
	 * @return the value of WF_ORG_MENU.MENU_CODE
	 */
	public String getMenuCode() {
		return menuCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_MENU.MENU_CODE
	 *
	 * @param menuCode
	 *            the value for WF_ORG_MENU.MENU_CODE
	 */
	public void setMenuCode(String menuCode) {
		this.menuCode = menuCode == null ? null : menuCode.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_MENU.PARENT_MENU_CODE
	 *
	 * @return the value of WF_ORG_MENU.PARENT_MENU_CODE
	 */
	public String getParentMenuCode() {
		return parentMenuCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_MENU.PARENT_MENU_CODE
	 *
	 * @param parentMenuCode
	 *            the value for WF_ORG_MENU.PARENT_MENU_CODE
	 */
	public void setParentMenuCode(String parentMenuCode) {
		this.parentMenuCode = parentMenuCode == null ? null : parentMenuCode.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_MENU.MENU_NAME
	 *
	 * @return the value of WF_ORG_MENU.MENU_NAME
	 */
	public String getMenuName() {
		return menuName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_MENU.MENU_NAME
	 *
	 * @param menuName
	 *            the value for WF_ORG_MENU.MENU_NAME
	 */
	public void setMenuName(String menuName) {
		this.menuName = menuName == null ? null : menuName.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_MENU.MENU_AREA
	 *
	 * @return the value of WF_ORG_MENU.MENU_AREA
	 */
	public String getMenuArea() {
		return menuArea;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_MENU.MENU_AREA
	 *
	 * @param menuArea
	 *            the value for WF_ORG_MENU.MENU_AREA
	 */
	public void setMenuArea(String menuArea) {
		this.menuArea = menuArea == null ? null : menuArea.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_MENU.MENU_LOCATION
	 *
	 * @return the value of WF_ORG_MENU.MENU_LOCATION
	 */
	public String getMenuLocation() {
		return menuLocation;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_MENU.MENU_LOCATION
	 *
	 * @param menuLocation
	 *            the value for WF_ORG_MENU.MENU_LOCATION
	 */
	public void setMenuLocation(String menuLocation) {
		this.menuLocation = menuLocation == null ? null : menuLocation.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_MENU.MENU_IMG_LOCATION
	 *
	 * @return the value of WF_ORG_MENU.MENU_IMG_LOCATION
	 */
	public String getMenuImgLocation() {
		return menuImgLocation;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_MENU.MENU_IMG_LOCATION
	 *
	 * @param menuImgLocation
	 *            the value for WF_ORG_MENU.MENU_IMG_LOCATION
	 */
	public void setMenuImgLocation(String menuImgLocation) {
		this.menuImgLocation = menuImgLocation == null ? null : menuImgLocation.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_MENU.MENU_DESC
	 *
	 * @return the value of WF_ORG_MENU.MENU_DESC
	 */
	public String getMenuDesc() {
		return menuDesc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_MENU.MENU_DESC
	 *
	 * @param menuDesc
	 *            the value for WF_ORG_MENU.MENU_DESC
	 */
	public void setMenuDesc(String menuDesc) {
		this.menuDesc = menuDesc == null ? null : menuDesc.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_MENU.MENU_ORDER
	 *
	 * @return the value of WF_ORG_MENU.MENU_ORDER
	 */
	public int getMenuOrder() {
		return menuOrder;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_MENU.MENU_ORDER
	 *
	 * @param menuOrder
	 *            the value for WF_ORG_MENU.MENU_ORDER
	 */
	public void setMenuOrder(int menuOrder) {
		this.menuOrder = menuOrder;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_MENU.MENU_ELEMENT_ID
	 *
	 * @return the value of WF_ORG_MENU.MENU_ELEMENT_ID
	 */
	public String getMenuElementId() {
		return menuElementId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_MENU.MENU_ELEMENT_ID
	 *
	 * @param menuElementId
	 *            the value for WF_ORG_MENU.MENU_ELEMENT_ID
	 */
	public void setMenuElementId(String menuElementId) {
		this.menuElementId = menuElementId == null ? null : menuElementId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_MENU.MENU_TYPE
	 *
	 * @return the value of WF_ORG_MENU.MENU_TYPE
	 */
	public String getMenuType() {
		return menuType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_MENU.MENU_TYPE
	 *
	 * @param menuType
	 *            the value for WF_ORG_MENU.MENU_TYPE
	 */
	public void setMenuType(String menuType) {
		this.menuType = menuType == null ? null : menuType.trim();
	}

	public void setMenuIsDefault(String menuIsDefault) {
		this.menuIsDefault = menuIsDefault;
	}

	public String getMenuIsDefault() {
		return menuIsDefault;
	}

	public void setMenuElementType(String menuElementType) {
		this.menuElementType = menuElementType;
	}

	public String getMenuElementType() {
		return menuElementType;
	}

	public void setMenuLevel(int menuLevel) {
		this.menuLevel = menuLevel;
	}

	public int getMenuLevel() {
		return menuLevel;
	}

	public void setUserID(String userID) {
		this.userID = userID;
	}

	public String getUserID() {
		return userID;
	}

	public void setMaxValue(int maxValue) {
		this.maxValue = maxValue;
	}

	public int getMaxValue() {
		return maxValue;
	}

	public void setUserIdTemp(List<String> userIdTemp) {
		this.userIdTemp = userIdTemp;
	}

	public List<String> getUserIdTemp() {
		return userIdTemp;
	}

	public void setAuthorityType(String authorityType) {
		this.authorityType = authorityType;
	}

	public String getAuthorityType() {
		return authorityType;
	}

	public void setRoleType(String roleType) {
		this.roleType = roleType;
	}

	public String getRoleType() {
		return roleType;
	}
}
