package centling.service.discount;

import java.util.Calendar;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;

import centling.business.Constant;
import centling.business.BlDiscountManager;
import centling.util.BlDateUtil;
import chinsoft.core.LogPrinter;

/**
 * 每月折扣返款定时任务
 *
 */
public class BlAutoDiscountTimeManager {
	public BlAutoDiscountTimeManager() {
		// 设置定时任务的执行时间
		Calendar calendar = Calendar.getInstance();
		calendar.set(Calendar.DAY_OF_MONTH, Constant.BL_AUTO_DISCOUNT_DAY);
		calendar.set(Calendar.HOUR_OF_DAY, Constant.BL_AUTO_DISCOUNT_HOUR);
		calendar.set(Calendar.MINUTE, Constant.BL_AUTO_DISCOUNT_MINUTE);
		calendar.set(Calendar.SECOND, Constant.BL_AUTO_DISCOUNT_SECOND);
		
		// 第一次执行任务的时间
		Date date = calendar.getTime();
		
		// 如果第一次执行定时任务的时间小于当前的时间
		// 此时要在第一次定时任务的时间加一个月，以便此任务在下个时间点执行
		// 如果不加一个月，任务会立即执行
		if(date.before(new Date())) {
			date = BlDateUtil.addMonth(date, 1);
		}
		
		Timer timer = new Timer();
		
		// 指定任务
		TimerTask autoDiscountTask = new TimerTask() {
			@Override
			public void run() {
				// 取得今天是这个月的几号
				int day = BlDateUtil.getMonthDay(new Date());
				
				// 如果今天是这个月的1号
				if (day == 1) {
					try {
						Date date = new Date();
						int retValue = new BlDiscountManager().autoGenerateDiscount(
								BlDateUtil.getTheFirstDateOfLastMonthStr(date), 
								BlDateUtil.getTheLastDateOfLastMonthStr(date)
								);
						if (retValue != 0) {
							LogPrinter.error("每月折扣返款异常");
						}
					} catch (Exception e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}
			}
		};
		
		// 指定定时任务
		timer.schedule(autoDiscountTask, date, Constant.BL_PERIOD_DAY);
	}
}