package com.dhc.organization.unit.domain;

import com.dhc.organization.common.data.BaseVO;

public class WF_ORG_DICTIONARY extends BaseVO {

	/**
	 * constructor
	 */
	public WF_ORG_DICTIONARY() {

	}

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_DICTIONARY.DICT_CODE
	 */
	private String dictCode;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_DICTIONARY.DICT_NAME
	 */
	private String dictName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_DICTIONARY.DICT_TYPE
	 */
	private String dictType;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_DICTIONARY.DICT_CODE
	 *
	 * @return the value of WF_ORG_DICTIONARY.DICT_CODE
	 */
	public String getDictCode() {
		return dictCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_DICTIONARY.DICT_CODE
	 *
	 * @param dictCode
	 *            the value for WF_ORG_DICTIONARY.DICT_CODE
	 */
	public void setDictCode(String dictCode) {
		this.dictCode = dictCode == null ? null : dictCode.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_DICTIONARY.DICT_NAME
	 *
	 * @return the value of WF_ORG_DICTIONARY.DICT_NAME
	 */
	public String getDictName() {
		return dictName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_DICTIONARY.DICT_NAME
	 *
	 * @param dictName
	 *            the value for WF_ORG_DICTIONARY.DICT_NAME
	 */
	public void setDictName(String dictName) {
		this.dictName = dictName == null ? null : dictName.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_DICTIONARY.DICT_TYPE
	 *
	 * @return the value of WF_ORG_DICTIONARY.DICT_TYPE
	 */
	public String getDictType() {
		return dictType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_DICTIONARY.DICT_TYPE
	 *
	 * @param dictType
	 *            the value for WF_ORG_DICTIONARY.DICT_TYPE
	 */
	public void setDictType(String dictType) {
		this.dictType = dictType == null ? null : dictType.trim();
	}
}