package cn.rkylin.oms.system.delegate.domain;


import java.util.ArrayList;
import java.util.List;

import cn.rkylin.oms.common.base.BaseEntity;


public class WF_ORG_DELEGATE extends BaseEntity{
	/**
	 * 序列
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_DELEGATE.DELE_ID
	 */
	private String deleId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_DELEGATE.USER_ID
	 */
	private String userId;

	private String currentUserId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_DELEGATE.TRUSTOR_ID
	 */
	private String trustorId;

	private String trustor_name;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_DELEGATE.DELE_NAME
	 */
	private String deleName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_DELEGATE.DELE_DESCRIPTION
	 */
	private String deleDescription;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_DELEGATE.DELE_TIME_BEGIN
	 */
	private String deleTimeBegin;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_DELEGATE.DELE_TIME_END
	 */
	private String deleTimeEnd;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_DELEGATE.DELE_ALL_PRIVIL
	 */
	private String deleAllPrivil;

	private List unitItemList = new ArrayList();

	private List stationItemList = new ArrayList();

	private List roleItemList = new ArrayList();

	private String userName;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_DELEGATE.DELE_ID
	 *
	 * @return the value of WF_ORG_DELEGATE.DELE_ID
	 */
	public String getDeleId() {
		return deleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_DELEGATE.DELE_ID
	 *
	 * @param deleId
	 *            the value for WF_ORG_DELEGATE.DELE_ID
	 */
	public void setDeleId(String deleId) {
		this.deleId = deleId == null ? null : deleId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_DELEGATE.USER_ID
	 *
	 * @return the value of WF_ORG_DELEGATE.USER_ID
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_DELEGATE.USER_ID
	 *
	 * @param userId
	 *            the value for WF_ORG_DELEGATE.USER_ID
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_DELEGATE.TRUSTOR_ID
	 *
	 * @return the value of WF_ORG_DELEGATE.TRUSTOR_ID
	 */
	public String getTrustorId() {
		return trustorId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_DELEGATE.TRUSTOR_ID
	 *
	 * @param trustorId
	 *            the value for WF_ORG_DELEGATE.TRUSTOR_ID
	 */
	public void setTrustorId(String trustorId) {
		this.trustorId = trustorId == null ? null : trustorId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_DELEGATE.DELE_NAME
	 *
	 * @return the value of WF_ORG_DELEGATE.DELE_NAME
	 */
	public String getDeleName() {
		return deleName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_DELEGATE.DELE_NAME
	 *
	 * @param deleName
	 *            the value for WF_ORG_DELEGATE.DELE_NAME
	 */
	public void setDeleName(String deleName) {
		this.deleName = deleName == null ? null : deleName.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_DELEGATE.DELE_DESCRIPTION
	 *
	 * @return the value of WF_ORG_DELEGATE.DELE_DESCRIPTION
	 */
	public String getDeleDescription() {
		return deleDescription;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_DELEGATE.DELE_DESCRIPTION
	 *
	 * @param deleDescription
	 *            the value for WF_ORG_DELEGATE.DELE_DESCRIPTION
	 */
	public void setDeleDescription(String deleDescription) {
		this.deleDescription = deleDescription == null ? null : deleDescription.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_DELEGATE.DELE_TIME_BEGIN
	 *
	 * @return the value of WF_ORG_DELEGATE.DELE_TIME_BEGIN
	 */
	public String getDeleTimeBegin() {
		return deleTimeBegin;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_DELEGATE.DELE_TIME_BEGIN
	 *
	 * @param deleTimeBegin
	 *            the value for WF_ORG_DELEGATE.DELE_TIME_BEGIN
	 */
	public void setDeleTimeBegin(String deleTimeBegin) {
		this.deleTimeBegin = deleTimeBegin;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_DELEGATE.DELE_TIME_END
	 *
	 * @return the value of WF_ORG_DELEGATE.DELE_TIME_END
	 */
	public String getDeleTimeEnd() {
		return deleTimeEnd;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_DELEGATE.DELE_TIME_END
	 *
	 * @param deleTimeEnd
	 *            the value for WF_ORG_DELEGATE.DELE_TIME_END
	 */
	public void setDeleTimeEnd(String deleTimeEnd) {
		this.deleTimeEnd = deleTimeEnd;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_DELEGATE.DELE_ALL_PRIVIL
	 *
	 * @return the value of WF_ORG_DELEGATE.DELE_ALL_PRIVIL
	 */
	public String getDeleAllPrivil() {
		return deleAllPrivil;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_DELEGATE.DELE_ALL_PRIVIL
	 *
	 * @param deleAllPrivil
	 *            the value for WF_ORG_DELEGATE.DELE_ALL_PRIVIL
	 */
	public void setDeleAllPrivil(String deleAllPrivil) {
		this.deleAllPrivil = deleAllPrivil == null ? null : deleAllPrivil.trim();
	}

	public void setUnitItemList(List unitItemList) {
		this.unitItemList = unitItemList;
	}

	public List getUnitItemList() {
		return unitItemList;
	}

	public void setStationItemList(List stationItemList) {
		this.stationItemList = stationItemList;
	}

	public List getStationItemList() {
		return stationItemList;
	}

	public void setRoleItemList(List roleItemList) {
		this.roleItemList = roleItemList;
	}

	public List getRoleItemList() {
		return roleItemList;
	}

	public void setTrustor_name(String trustor_name) {
		this.trustor_name = trustor_name;
	}

	public String getTrustor_name() {
		return trustor_name;
	}

	public void setCurrentUserId(String currentUserId) {
		this.currentUserId = currentUserId;
	}

	public String getCurrentUserId() {
		return currentUserId;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserName() {
		return userName;
	}

}
