package cn.rkylin.oms.system.station.domain;

import java.util.Date;
import java.util.List;

import cn.rkylin.oms.common.base.BaseEntity;

public class WF_ORG_STATION extends BaseEntity{
	/**
	 * 
	 */
	private static final long serialVersionUID = 6716243072800180864L;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_STATION.STATION_ID
	 */
	private String stationId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_STATION.UNIT_ID
	 */
	private String unitId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_STATION.PARENT_STATION_ID
	 */
	private String parentStationId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_STATION.STATION_NAME
	 */
	private String stationName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_STATION.STATION_DESCRIPTION
	 */
	private String stationDescription;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_STATION.STATION_TIME_BEGIN
	 */
	private Date stationTimeBegin;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_STATION.STATION_TIME_END
	 */
	private Date stationTimeEnd;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_STATION.USER_NUMBERS
	 */
	private Long userNumbers;

	/**
	 * 岗位下的所有用户WF_ORG_USER_STATION
	 */
	private List stationUser;

	/**
	 * 存放返回的user字符串
	 */
	private String stationUsers;

	/**
	 * 作为查询条件，用于查询用户的所有岗位
	 */
	private String userId;

	/**
	 * 用于查询该岗位是否可以管理(true代表是否可管理，会查询全部数据)
	 */
	private String managable;

	/**
	 * 用于查询被委托的岗位，仅在登录、权限判断时使用。
	 */
	private List<String> delegateStationIdList;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_STATION.STATION_ID
	 *
	 * @return the value of WF_ORG_STATION.STATION_ID
	 */
	public String getStationId() {
		return stationId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_STATION.STATION_ID
	 *
	 * @param stationId
	 *            the value for WF_ORG_STATION.STATION_ID
	 */
	public void setStationId(String stationId) {
		this.stationId = stationId == null ? null : stationId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_STATION.UNIT_ID
	 *
	 * @return the value of WF_ORG_STATION.UNIT_ID
	 */
	public String getUnitId() {
		return unitId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_STATION.UNIT_ID
	 *
	 * @param unitId
	 *            the value for WF_ORG_STATION.UNIT_ID
	 */
	public void setUnitId(String unitId) {
		this.unitId = unitId == null ? null : unitId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_STATION.PARENT_STATION_ID
	 *
	 * @return the value of WF_ORG_STATION.PARENT_STATION_ID
	 */
	public String getParentStationId() {
		return parentStationId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_STATION.PARENT_STATION_ID
	 *
	 * @param parentStationId
	 *            the value for WF_ORG_STATION.PARENT_STATION_ID
	 */
	public void setParentStationId(String parentStationId) {
		this.parentStationId = parentStationId == null ? null : parentStationId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_STATION.STATION_NAME
	 *
	 * @return the value of WF_ORG_STATION.STATION_NAME
	 */
	public String getStationName() {
		return stationName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_STATION.STATION_NAME
	 *
	 * @param stationName
	 *            the value for WF_ORG_STATION.STATION_NAME
	 */
	public void setStationName(String stationName) {
		this.stationName = stationName == null ? null : stationName.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_STATION.STATION_DESCRIPTION
	 *
	 * @return the value of WF_ORG_STATION.STATION_DESCRIPTION
	 */
	public String getStationDescription() {
		return stationDescription;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_STATION.STATION_DESCRIPTION
	 *
	 * @param stationDescription
	 *            the value for WF_ORG_STATION.STATION_DESCRIPTION
	 */
	public void setStationDescription(String stationDescription) {
		this.stationDescription = stationDescription == null ? null : stationDescription.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_STATION.STATION_TIME_BEGIN
	 *
	 * @return the value of WF_ORG_STATION.STATION_TIME_BEGIN
	 */
	public Date getStationTimeBegin() {
		return stationTimeBegin;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_STATION.STATION_TIME_BEGIN
	 *
	 * @param stationTimeBegin
	 *            the value for WF_ORG_STATION.STATION_TIME_BEGIN
	 */
	public void setStationTimeBegin(Date stationTimeBegin) {
		this.stationTimeBegin = stationTimeBegin;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_STATION.STATION_TIME_END
	 *
	 * @return the value of WF_ORG_STATION.STATION_TIME_END
	 */
	public Date getStationTimeEnd() {
		return stationTimeEnd;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_STATION.STATION_TIME_END
	 *
	 * @param stationTimeEnd
	 *            the value for WF_ORG_STATION.STATION_TIME_END
	 */
	public void setStationTimeEnd(Date stationTimeEnd) {
		this.stationTimeEnd = stationTimeEnd;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_STATION.USER_NUMBERS
	 *
	 * @return the value of WF_ORG_STATION.USER_NUMBERS
	 */
	public Long getUserNumbers() {
		return userNumbers;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_STATION.USER_NUMBERS
	 *
	 * @param userNumbers
	 *            the value for WF_ORG_STATION.USER_NUMBERS
	 */
	public void setUserNumbers(Long userNumbers) {
		this.userNumbers = userNumbers;
	}

	public List getStationUser() {
		return stationUser;
	}

	public void setStationUser(List stationUser) {
		this.stationUser = stationUser;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserId() {
		return userId;
	}

	public void setStationUsers(String stationUsers) {
		this.stationUsers = stationUsers;
	}

	public String getStationUsers() {
		return stationUsers;
	}

	public String getManagable() {
		return managable;
	}

	public void setManagable(String managable) {
		this.managable = managable;
	}

	public void setDelegateStationIdList(List<String> delegateStationIdList) {
		this.delegateStationIdList = delegateStationIdList;
	}

	public List<String> getDelegateStationIdList() {
		return delegateStationIdList;
	}

}