
package com.service.cn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShipWebService", targetNamespace = "http://webservice.ciqqlc.dpn.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShipWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.service.cn.ServiceResult
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice.ciqqlc.dpn.com/ShipWebService/vslDecServiceRequest", output = "http://webservice.ciqqlc.dpn.com/ShipWebService/vslDecServiceResponse")
    public ServiceResult vslDecService(
        @WebParam(name = "arg0", partName = "arg0")
        VslDecIo arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.service.cn.ServiceResult
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice.ciqqlc.dpn.com/ShipWebService/vslAprServiceRequest", output = "http://webservice.ciqqlc.dpn.com/ShipWebService/vslAprServiceResponse")
    public ServiceResult vslAprService(
        @WebParam(name = "arg0", partName = "arg0")
        VslUpdateDecIo arg0);

}
