<%
'-----------------------------------------------------------------------------
'		EGMAIN-EX Access ActiveX Include File (Ver0.0.1)
'		AUTHER  : Ishihara@fsit.fujitsu.com
'-----------------------------------------------------------------------------
%>
<OBJECT ID="KarteAccessMain" CLASSID="CLSID:02EE58FE-4411-11D6-B23C-00E0006FB3ED" CODEBASE="/webHains/cab/KarteAccess/KarteAccess.CAB#version=1,0,0,13"></OBJECT>
