<%
'-----------------------------------------------------------------------------
'		web—\–ñî•ñ“o˜^—p Include File (Ver1.0.0)
'	   AUTHER  : Tsutomu Takagi@fsit.fujitsu.com
'-----------------------------------------------------------------------------
'’è”’è‹`
Const PERID_FOR_NEW_PERSON = "yV‹Kz"	'V‹KŽófŽÒ—p‚ÌŒÂlID—“•\Ž¦ƒeƒLƒXƒg

Const REGFLG_UNREGIST = "1"	'–{“o˜^ƒtƒ‰ƒO(–¢“o˜^ŽÒ)
Const REGFLG_REGIST   = "2"	'–{“o˜^ƒtƒ‰ƒO(•ÒWÏ‚ÝŽófŽÒ)
%>
