package com.dhc.organization.user.domain;

import java.util.Date;
import java.util.List;
import java.util.Map;

import com.dhc.organization.common.data.BaseVO;

public class WF_ORG_USER extends BaseVO {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_USER.USER_ID
	 */
	private String userId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_USER.USER_ACCOUNT
	 */
	private String userAccount;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_USER.USER_FULLNAME
	 */
	private String userFullname;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_USER.USER_PASSWORD
	 */
	private String userPassword;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_USER.USER_DESCRIPTION
	 */
	private String userDescription;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_USER.USER_PASSWORD_CHANGED
	 */
	private Date userPasswordChanged;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_USER.USER_ACCOUNT_ENABLED
	 */
	private String userAccountEnabled;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_USER.USER_ACCOUNT_LOCKED
	 */
	private String userAccountLocked;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_USER.USER_ACCOUNT_CREATED
	 */
	private Date userAccountCreated;

	// WF_ORG_USER_UNIT
	private List userUnitList;

	// WF_ORG_USER_STATION
	private List userStationList;

	// WF_ORG_USER_ROLE
	private List<String> userRoleList;

	// WF_ORG_ROLE
	private List roleList;

	// WF_ORG_STATION
	private List stationList;

	// WF_ORG_UNIT
	private List unitList;

	// 所属组织单元，作为parameterClass中的条件
	private String unitID;

	// 作为查询条件，用于查询角色下的所有用户
	private String roleId;

	// 存放用户所在的组织单元
	private String userUnits;

	// 用于根据用户id查询用户，存放用户id字符串，id使用“,”分隔
	private List<String> userIds;

	// 存放用户所在的角色
	private String userRoles;

	// 作为查询条件，用于查询岗位下的用户
	private String stationId;

	// 作为存放扩展信息
	private Map extInfoMap;

	// 仅作为查询条件，用于获取人员列表时的人员类型“管理员,adminUser”，“普通用户bizUser”（使用角色来判断）
	private String userType;

	// 作为查询条件，用于查询管理角色可管理组织单元下的人员
	private String adminRoleID;

	// 作为查询条件，用于判断当前执行查询的用户是否是adminUser（管理员可以看到所有的人）
	private String currentLoginUserID;

	public String getUnitID() {
		return unitID;
	}

	public void setUnitID(String unitID) {
		this.unitID = unitID;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_USER.USER_ID
	 *
	 * @return the value of WF_ORG_USER.USER_ID
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_USER.USER_ID
	 *
	 * @param userId
	 *            the value for WF_ORG_USER.USER_ID
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_USER.USER_ACCOUNT
	 *
	 * @return the value of WF_ORG_USER.USER_ACCOUNT
	 */
	public String getUserAccount() {
		return userAccount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_USER.USER_ACCOUNT
	 *
	 * @param userAccount
	 *            the value for WF_ORG_USER.USER_ACCOUNT
	 */
	public void setUserAccount(String userAccount) {
		this.userAccount = userAccount == null ? null : userAccount.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_USER.USER_FULLNAME
	 *
	 * @return the value of WF_ORG_USER.USER_FULLNAME
	 */
	public String getUserFullname() {
		return userFullname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_USER.USER_FULLNAME
	 *
	 * @param userFullname
	 *            the value for WF_ORG_USER.USER_FULLNAME
	 */
	public void setUserFullname(String userFullname) {
		this.userFullname = userFullname == null ? null : userFullname.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_USER.USER_PASSWORD
	 *
	 * @return the value of WF_ORG_USER.USER_PASSWORD
	 */
	public String getUserPassword() {
		return userPassword;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_USER.USER_PASSWORD
	 *
	 * @param userPassword
	 *            the value for WF_ORG_USER.USER_PASSWORD
	 */
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword == null ? null : userPassword.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_USER.USER_DESCRIPTION
	 *
	 * @return the value of WF_ORG_USER.USER_DESCRIPTION
	 */
	public String getUserDescription() {
		return userDescription;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_USER.USER_DESCRIPTION
	 *
	 * @param userDescription
	 *            the value for WF_ORG_USER.USER_DESCRIPTION
	 */
	public void setUserDescription(String userDescription) {
		this.userDescription = userDescription == null ? null : userDescription.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_USER.USER_PASSWORD_CHANGED
	 *
	 * @return the value of WF_ORG_USER.USER_PASSWORD_CHANGED
	 */
	public Date getUserPasswordChanged() {
		return userPasswordChanged;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_USER.USER_PASSWORD_CHANGED
	 *
	 * @param userPasswordChanged
	 *            the value for WF_ORG_USER.USER_PASSWORD_CHANGED
	 */
	public void setUserPasswordChanged(Date userPasswordChanged) {
		this.userPasswordChanged = userPasswordChanged;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_USER.USER_ACCOUNT_ENABLED
	 *
	 * @return the value of WF_ORG_USER.USER_ACCOUNT_ENABLED
	 */
	public String getUserAccountEnabled() {
		return userAccountEnabled;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_USER.USER_ACCOUNT_ENABLED
	 *
	 * @param userAccountEnabled
	 *            the value for WF_ORG_USER.USER_ACCOUNT_ENABLED
	 */
	public void setUserAccountEnabled(String userAccountEnabled) {
		this.userAccountEnabled = userAccountEnabled == null ? null : userAccountEnabled.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_USER.USER_ACCOUNT_LOCKED
	 *
	 * @return the value of WF_ORG_USER.USER_ACCOUNT_LOCKED
	 */
	public String getUserAccountLocked() {
		return userAccountLocked;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_USER.USER_ACCOUNT_LOCKED
	 *
	 * @param userAccountLocked
	 *            the value for WF_ORG_USER.USER_ACCOUNT_LOCKED
	 */
	public void setUserAccountLocked(String userAccountLocked) {
		this.userAccountLocked = userAccountLocked == null ? null : userAccountLocked.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_USER.USER_ACCOUNT_CREATED
	 *
	 * @return the value of WF_ORG_USER.USER_ACCOUNT_CREATED
	 */
	public Date getUserAccountCreated() {
		return userAccountCreated;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_USER.USER_ACCOUNT_CREATED
	 *
	 * @param userAccountCreated
	 *            the value for WF_ORG_USER.USER_ACCOUNT_CREATED
	 */
	public void setUserAccountCreated(Date userAccountCreated) {
		this.userAccountCreated = userAccountCreated;
	}

	public List getUserUnitList() {
		return userUnitList;
	}

	public void setUserUnitList(List userUnitList) {
		this.userUnitList = userUnitList;
	}

	public List getUserStationList() {
		return userStationList;
	}

	public void setUserStationList(List userStationList) {
		this.userStationList = userStationList;
	}

	public List<String> getUserRoleList() {
		return userRoleList;
	}

	public void setUserRoleList(List<String> userRoleList) {
		this.userRoleList = userRoleList;
	}

	public List getRoleList() {
		return roleList;
	}

	public void setRoleList(List roleList) {
		this.roleList = roleList;
	}

	public List getStationList() {
		return stationList;
	}

	public void setStationList(List stationList) {
		this.stationList = stationList;
	}

	public List getUnitList() {
		return unitList;
	}

	public void setUnitList(List unitList) {
		this.unitList = unitList;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getRoleId() {
		return roleId;
	}

	public void setUserUnits(String userUnits) {
		this.userUnits = userUnits;
	}

	public String getUserUnits() {
		return userUnits;
	}

	public void setUserIds(List<String> userIds) {
		this.userIds = userIds;
	}

	public List<String> getUserIds() {
		return userIds;
	}

	public void setUserRoles(String userRoles) {
		this.userRoles = userRoles;
	}

	public String getUserRoles() {
		return userRoles;
	}

	public void setStationId(String stationId) {
		this.stationId = stationId;
	}

	public String getStationId() {
		return stationId;
	}

	public void setExtInfoMap(Map extInfoMap) {
		this.extInfoMap = extInfoMap;
	}

	public Map getExtInfoMap() {
		return extInfoMap;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public String getUserType() {
		return userType;
	}

	public void setAdminRoleID(String adminRoleID) {
		this.adminRoleID = adminRoleID;
	}

	public String getAdminRoleID() {
		return adminRoleID;
	}

	public void setCurrentLoginUserID(String currentLoginUserID) {
		this.currentLoginUserID = currentLoginUserID;
	}

	public String getCurrentLoginUserID() {
		return currentLoginUserID;
	}

}