
package com.test.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShipWebService", targetNamespace = "http://webservice.ciqqlc.dpn.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShipWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.test.client.ServiceResult
     */
    @WebMethod
    @WebResult(partName = "return")
    public ServiceResult vslAprService(
        @WebParam(name = "arg0", partName = "arg0")
        VslUpdateDecIo arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.test.client.ServiceResult
     */
    @WebMethod
    @WebResult(partName = "return")
    public ServiceResult vslDecService(
        @WebParam(name = "arg0", partName = "arg0")
        VslDecIo arg0);

}
