package chinsoft.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2014-04-26T10:39:03.271+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://services.redcollar.cn/", name = "IServiceToLogistics")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IServiceToLogistics {

    @WebResult(name = "return", targetNamespace = "http://services.redcollar.cn/", partName = "return")
    @WebMethod
    public java.lang.String doSaveLogistic(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );
}
