package cn.rkylin.oms.system.privilege.domain;

import java.util.List;

import cn.rkylin.oms.common.base.BaseEntity;


public class WF_ORG_RESOURCE_AUTHORITY extends BaseEntity {
	/**
	 * 序列化
	 */
	private static final long serialVersionUID = 2190108829491233180L;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_RESOURCE_AUTHORITY.RESOURCE_AUTHORITY_ID
	 */
	private String resourceAuthorityId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_RESOURCE_AUTHORITY.AUTHORITY_DESC
	 */
	private String authorityDesc;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_RESOURCE_AUTHORITY.ROLE_ID
	 */
	private String roleId;

	private List<String> roleIdTem;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_RESOURCE_AUTHORITY.ROLE_TYPE
	 */
	private String roleType;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_RESOURCE_AUTHORITY.RESOURCE_ID
	 */
	private String resourceId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_RESOURCE_AUTHORITY.AUTHORITY_TYPE
	 */
	private String authorityType;

	/**
	 * 用于作为查询条件，查询菜单项下(仅一级)菜单项和页面元素的可用性。
	 */
	private String menuId;

	/**
	 * 作为查询条件，用于查询菜单树结点下级结点是否授权
	 */
	private String parentMenuCode;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column
	 * WF_ORG_RESOURCE_AUTHORITY.RESOURCE_AUTHORITY_ID
	 *
	 * @return the value of WF_ORG_RESOURCE_AUTHORITY.RESOURCE_AUTHORITY_ID
	 */
	public String getResourceAuthorityId() {
		return resourceAuthorityId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column
	 * WF_ORG_RESOURCE_AUTHORITY.RESOURCE_AUTHORITY_ID
	 *
	 * @param resourceAuthorityId
	 *            the value for WF_ORG_RESOURCE_AUTHORITY.RESOURCE_AUTHORITY_ID
	 */
	public void setResourceAuthorityId(String resourceAuthorityId) {
		this.resourceAuthorityId = resourceAuthorityId == null ? null : resourceAuthorityId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_RESOURCE_AUTHORITY.AUTHORITY_DESC
	 *
	 * @return the value of WF_ORG_RESOURCE_AUTHORITY.AUTHORITY_DESC
	 */
	public String getAuthorityDesc() {
		return authorityDesc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_RESOURCE_AUTHORITY.AUTHORITY_DESC
	 *
	 * @param authorityDesc
	 *            the value for WF_ORG_RESOURCE_AUTHORITY.AUTHORITY_DESC
	 */
	public void setAuthorityDesc(String authorityDesc) {
		this.authorityDesc = authorityDesc == null ? null : authorityDesc.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_RESOURCE_AUTHORITY.ROLE_ID
	 *
	 * @return the value of WF_ORG_RESOURCE_AUTHORITY.ROLE_ID
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_RESOURCE_AUTHORITY.ROLE_ID
	 *
	 * @param roleId
	 *            the value for WF_ORG_RESOURCE_AUTHORITY.ROLE_ID
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId == null ? null : roleId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_RESOURCE_AUTHORITY.ROLE_TYPE
	 *
	 * @return the value of WF_ORG_RESOURCE_AUTHORITY.ROLE_TYPE
	 */
	public String getRoleType() {
		return roleType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_RESOURCE_AUTHORITY.ROLE_TYPE
	 *
	 * @param roleType
	 *            the value for WF_ORG_RESOURCE_AUTHORITY.ROLE_TYPE
	 */
	public void setRoleType(String roleType) {
		this.roleType = roleType == null ? null : roleType.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_RESOURCE_AUTHORITY.RESOURCE_ID
	 *
	 * @return the value of WF_ORG_RESOURCE_AUTHORITY.RESOURCE_ID
	 */
	public String getResourceId() {
		return resourceId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_RESOURCE_AUTHORITY.RESOURCE_ID
	 *
	 * @param resourceId
	 *            the value for WF_ORG_RESOURCE_AUTHORITY.RESOURCE_ID
	 */
	public void setResourceId(String resourceId) {
		this.resourceId = resourceId == null ? null : resourceId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_RESOURCE_AUTHORITY.AUTHORITY_TYPE
	 *
	 * @return the value of WF_ORG_RESOURCE_AUTHORITY.AUTHORITY_TYPE
	 */
	public String getAuthorityType() {
		return authorityType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_RESOURCE_AUTHORITY.AUTHORITY_TYPE
	 *
	 * @param authorityType
	 *            the value for WF_ORG_RESOURCE_AUTHORITY.AUTHORITY_TYPE
	 */
	public void setAuthorityType(String authorityType) {
		this.authorityType = authorityType == null ? null : authorityType.trim();
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	public String getMenuId() {
		return menuId;
	}

	public void setParentMenuCode(String parentMenuCode) {
		this.parentMenuCode = parentMenuCode;
	}

	public String getParentMenuCode() {
		return parentMenuCode;
	}

	public void setRoleIdTem(List<String> roleIdTem) {
		this.roleIdTem = roleIdTem;
	}

	public List<String> getRoleIdTem() {
		return roleIdTem;
	}
}