package com.dhc.organization.unit.domain;

import java.util.List;
import java.util.Map;

import com.dhc.organization.common.data.BaseVO;

public class WF_ORG_UNIT extends BaseVO {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_UNIT.UNIT_ID
	 */
	private String unitId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_UNIT.PARENT_UNIT_ID
	 */
	private String parentUnitId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_UNIT.STATION_ID
	 */
	private String stationId;

	/**
	 * 岗位名称
	 */
	private String stationName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_UNIT.UNIT_NAME
	 */
	private String unitName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_UNIT.UNIT_DESCRIPTION
	 */
	private String unitDescription;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column WF_ORG_UNIT.UNIT_TYPE
	 */
	private String unitType;

	/**
	 * 作为查询条件，用于表示该组织单元是否可以被管理
	 */
	private String manageable;

	/**
	 * 作为查询条件，用于查询用户的所有组织
	 */
	private String userId;

	/**
	 * 组织中的所有用户
	 */
	private List userList;

	/**
	 * 作为查询条件，用于查询角色可以管理的组织单元
	 */
	private String roleId;

	/**
	 * 用于保存扩展信息
	 */
	private Map extInfoMap;

	/**
	 * 用于查询被委托的组织，仅在登录、权限判断时使用。
	 */
	private List<String> delegateUnitIdList;

	// 组织下的用户，对应 WF_ORG_USER_UNIT
	private String[] unitUsersArray;

	public String getManageable() {
		return manageable;
	}

	public void setManageable(String manageable) {
		this.manageable = manageable;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_UNIT.UNIT_ID
	 *
	 * @return the value of WF_ORG_UNIT.UNIT_ID
	 */
	public String getUnitId() {
		return unitId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_UNIT.UNIT_ID
	 *
	 * @param unitId
	 *            the value for WF_ORG_UNIT.UNIT_ID
	 */
	public void setUnitId(String unitId) {
		this.unitId = unitId == null ? null : unitId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_UNIT.PARENT_UNIT_ID
	 *
	 * @return the value of WF_ORG_UNIT.PARENT_UNIT_ID
	 */
	public String getParentUnitId() {
		return parentUnitId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_UNIT.PARENT_UNIT_ID
	 *
	 * @param parentUnitId
	 *            the value for WF_ORG_UNIT.PARENT_UNIT_ID
	 */
	public void setParentUnitId(String parentUnitId) {
		this.parentUnitId = parentUnitId == null ? null : parentUnitId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_UNIT.STATION_ID
	 *
	 * @return the value of WF_ORG_UNIT.STATION_ID
	 */
	public String getStationId() {
		return stationId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_UNIT.STATION_ID
	 *
	 * @param stationId
	 *            the value for WF_ORG_UNIT.STATION_ID
	 */
	public void setStationId(String stationId) {
		this.stationId = stationId == null ? null : stationId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_UNIT.UNIT_NAME
	 *
	 * @return the value of WF_ORG_UNIT.UNIT_NAME
	 */
	public String getUnitName() {
		return unitName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_UNIT.UNIT_NAME
	 *
	 * @param unitName
	 *            the value for WF_ORG_UNIT.UNIT_NAME
	 */
	public void setUnitName(String unitName) {
		this.unitName = unitName == null ? null : unitName.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_UNIT.UNIT_DESCRIPTION
	 *
	 * @return the value of WF_ORG_UNIT.UNIT_DESCRIPTION
	 */
	public String getUnitDescription() {
		return unitDescription;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_UNIT.UNIT_DESCRIPTION
	 *
	 * @param unitDescription
	 *            the value for WF_ORG_UNIT.UNIT_DESCRIPTION
	 */
	public void setUnitDescription(String unitDescription) {
		this.unitDescription = unitDescription == null ? null : unitDescription.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column WF_ORG_UNIT.UNIT_TYPE
	 *
	 * @return the value of WF_ORG_UNIT.UNIT_TYPE
	 */
	public String getUnitType() {
		return unitType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column WF_ORG_UNIT.UNIT_TYPE
	 *
	 * @param unitType
	 *            the value for WF_ORG_UNIT.UNIT_TYPE
	 */
	public void setUnitType(String unitType) {
		this.unitType = unitType == null ? null : unitType.trim();
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserId() {
		return userId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getRoleId() {
		return roleId;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	public String getStationName() {
		return stationName;
	}

	public void setUserList(List userList) {
		this.userList = userList;
	}

	public List getUserList() {
		return userList;
	}

	public void setUnitUsersArray(String[] unitUsersArray) {
		this.unitUsersArray = unitUsersArray;
	}

	public String[] getUnitUsersArray() {
		return unitUsersArray;
	}

	public void setExtInfoMap(Map extInfoMap) {
		this.extInfoMap = extInfoMap;
	}

	public Map getExtInfoMap() {
		return extInfoMap;
	}

	public List<String> getDelegateUnitIdList() {
		return delegateUnitIdList;
	}

	public void setDelegateUnitIdList(List<String> delegateUnitIdList) {
		this.delegateUnitIdList = delegateUnitIdList;
	}
}