
package cn.mytest.sv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShipWebServiceImplService", targetNamespace = "http://cn.service.com/", wsdlLocation = "http://192.168.1.103:8081/webService/service/vslAprService?wsdl")
public class ShipWebServiceImplService
    extends Service
{

    private final static URL SHIPWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SHIPWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SHIPWEBSERVICEIMPLSERVICE_QNAME = new QName("http://cn.service.com/", "ShipWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.103:8081/webService/service/vslAprService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHIPWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SHIPWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ShipWebServiceImplService() {
        super(__getWsdlLocation(), SHIPWEBSERVICEIMPLSERVICE_QNAME);
    }

    public ShipWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHIPWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public ShipWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SHIPWEBSERVICEIMPLSERVICE_QNAME);
    }

    public ShipWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHIPWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public ShipWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShipWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ShipWebService
     */
    @WebEndpoint(name = "ShipWebServiceImplPort")
    public ShipWebService getShipWebServiceImplPort() {
        return super.getPort(new QName("http://cn.service.com/", "ShipWebServiceImplPort"), ShipWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShipWebService
     */
    @WebEndpoint(name = "ShipWebServiceImplPort")
    public ShipWebService getShipWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cn.service.com/", "ShipWebServiceImplPort"), ShipWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHIPWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SHIPWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SHIPWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
