SELECT ss.id AS coId,ss.NAME as coName,a.DEFINE_STATUS,a.riskNum 
		FROM (SELECT id,"NAME" FROM SYS_OFFICE WHERE DEL_FLAG = '0') ss
		LEFT JOIN 
		(SELECT BIZ_OPER_POST,DEFINE_STATUS,count(1) AS riskNum FROM DCA_RISK_MANAGE GROUP BY BIZ_OPER_POST,DEFINE_STATUS) a
		ON a.BIZ_OPER_POST = SS.id
		ORDER BY coId,a.DEFINE_STATUS