SELECT 
		ss.id AS coId,
		ss.NAME AS NAME,
		a.RISK_LEVEL,
		a.riskNum 
				
FROM (SELECT ID,NAME FROM SYS_OFFICE WHERE DEL_FLAG = '0') ss
LEFT JOIN (SELECT RISK_LEVEL,count(1) AS riskNum,BIZ_OPER_POST FROM DCA_RISK_MANAGE GROUP BY RISK_LEVEL,BIZ_OPER_POST) a
ON a.BIZ_OPER_POST = SS.ID
ORDER BY NAME,a.RISK_LEVEL