VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "Calc_C_Record"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Key              As String
Public Gender           As String
Public Variable1        As String
Public CalcItemCd1      As String
Public CalcSuffix1      As String
Public CalcItemName1    As String
Public Constant1        As String
Public Operator         As String
Public Variable2        As String
Public CalcItemCd2      As String
Public CalcSuffix2      As String
Public CalcItemName2    As String
Public Constant2        As String
Public CalcResult       As String

